EduTrack/EduTrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('plots/',include("plots.urls")),
]

EduTrack/home/urls.py
from django.urls import path
from .views import home,login,validate,register,add_user,plot,ret,logout

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('validate/', validate, name='validate'),
    path('register/', register, name='register'),
    path('add_user/', add_user, name='add_user'),
    path('plot/<str:p1>/<str:p2>/', plot, name='plot'),
    path('ret/', ret, name='ret'),
    path('logout/', logout, name='logout'),
]

EduTrack/plots/urls.py
from django.urls import path
from .views import read_data

app_name = 'plots'

urlpatterns = [
    path('read_data/', read_data, name='read_data'),
]

EduTrack/home/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length = 30,primary_key=True)
    password = models.CharField(max_length = 30)

    class Meta:
        db_table = "User"

EduTrack/plots/models.py
from django.db import models

# Create your models here.

EduTrack/home/views.py
from django.shortcuts import render
from django.template.context_processors import csrf
from .models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import csv
import plotly.graph_objects as go
import plotly.express as px
import plotly
import os
import pandas as pd

def home(request):
    return render(request,"home/home.html",{})

def login(request):
    return render(request,'home/login.html',{})

def validate(request):
    if(request.method=='POST'):
        username = request.POST.get('username','')
        password = request.POST.get('pass','')
        if(username is not None and password is not None):
            # flag1 = False
            # flag2 = False
            try:
                u = User.objects.get(username = username)
            except:
                messages.error(request,"Invalid Username")
                return render(request,'home/login.html') 

            if(u.password == password):
                request.session['username'] = username
                # request.session['password'] = password
                uname={
                    "username":username
                }      
                return render(request,'home/visualize.html', uname)
            else:
                messages.error(request,"Invalid Password")
                return render(request,'home/login.html')    
        else:
            messages.success(request,'Credentials cannot be empty')
            return render(request,'home/login.html')
    
    elif(request.method == "GET"):
        if(request.session.get('username',False)):
            username = request.session.get('username',False)
            uname={
                    "username":username
            }     
            return render(request,'home/login.html', uname)    
    
    else:
        return render(request,'home/login.html')

def register(request):
    return render(request,"home/registration.html",{})


def add_user(request):
    if(request.method=='POST'):
        username = request.POST.get('username','')
        password = request.POST.get('password','')
    u = User()
    u.username = username
    u.password = password
    u.save()
    return render(request,"home/login.html",{})


def plot(request,p1,p2):

    if(request.session.get('username',False)):
        username = request.session.get('username',False)
        uname={
                    "username":username
            }

        if p1=='phd' or p1=='mphil' or p1=='pg':
            fi='StateWise_Enrollment1.csv'
        else: 
            fi='StateWise_Enrollment2.csv'

        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        csv_file_path = os.path.join(base_dir, 'assets', fi)

        if p1=='phd' or p1=='ug':
            c1,c2=2,3
        if p1=='mphil' or p1=='pgdi':
            c1,c2=5,6
        if p1=='pg' or p1=='di':
            c1,c2=8,9


        with open(csv_file_path) as file:
            csvfile = csv.reader(file)
            M = []
            header = next(csvfile)
            next(csvfile)
            state_names = []
            for row in csvfile:
                M.append(row[:-1])
                state_names.append(row[1])
        
        male = list(map(lambda r: int(r[c1]) if r[c1] != '' else 0, M))
        female = list(map(lambda r: int(r[c2]) if r[c2] != '' else 0, M))

        male = male[:-1]
        female = female[:-1]
        state_names = state_names[:-1]
        
        if p2=='0':
            trace1 = go.Bar(x=state_names, y=male, name='Male', marker=dict(color='blue'))
            trace2 = go.Bar(x=state_names, y=female, name='Female', marker=dict(color='pink'))
            layout = go.Layout(barmode='stack', title=f'Enrollment of male and female',height=900,  width=1200)
            fig = go.Figure(data=[trace2, trace1], layout=layout)
            # fig.show()
            t=plotly.offline.plot(fig,auto_open=False,output_type='div')

        else:
            data = {'State':state_names ,
                'Male': male,
                'Female': female,
            }

            df = pd.DataFrame(data)

            df_melted = pd.melt(df, id_vars=['State'], var_name='Category', value_name='Value')

            # Create a nested pie chart
            fig = px.sunburst(df_melted, path=['State', 'Category'], values='Value',
                            title=f'Nested Pie Chart: Education Level by Gender and State',height=900,width=1200)

            # fig.show()
            t=plotly.offline.plot(fig,auto_open=False,output_type='div')
        

        return render(request,"home/showplot.html",{'t':t,'username':username})
    else:
        messages.info(request,"Login Required")
        return render(request,'home/login.html')


def ret(request):
    if(request.session.get('username',False)):
        username = request.session.get('username',False)
        uname={
                    "username":username
            }
        return render(request,"home/visualize.html",{})
    else:
        messages.info(request,"Login Required")
        return render(request,'home/login.html')


def logout(request):
    request.session.flush()
    messages.success(request,'logout successful')
    return render(request,"home/home.html",{})

EduTrack/plots/views.py
from django.shortcuts import render
import pandas as pd
import numpy as np


def read_data(request):
    data = pd.read_csv('EduTrack/media/StateWise_Enrollment1.csv')
    print(data.head())   
    return render()

EduTrack/home/templates/home/home.html
{% load static %}

<!DOCTYPE HTML>

<html>
	<head>
		<title>Home</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'home/assets/css/main.css' %}" />
	</head>
	<body class="is-preload" style="height: 80vh;">

		<!-- Header -->
			<section id="header">
				<header class="major">
					<h1>EduTrack</h1>
					<p>Visualize Student Statistics Here</p>
				</header>
				<div class="container" style="background-color: rgba(255, 255, 255, 0);">
					<ul class="actions special">
						<li><a href="{% url 'home:login' %}" class="button primary scrolly">Login</a></li>
						<li><a href="{% url 'home:register' %}" class="button primary scrolly">Register</a></li>
					</ul>
				</div>
				<!-- <div class="container">
					<ul class="actions special">
						<li><a href="{% url 'home:register' %}" class="button primary scrolly">Register</a></li>
					</ul>
				</div> -->
			</section>

		
		<!-- One -->
			<!-- <section id="one" class="main special">
				<div class="container">
					<span class="image fit primary"><img src="" alt="" /></span>
					<div class="content">
						<header class="major">
							<h2>About The Data</h2>
						</header>
						<p>You can get to know about what number of students have enrolled in different fields and at various levels of education. </p>
					</div>
					<a href="#two" class="goto-next scrolly">Next</a>
				</div>
			</section> -->

		<!-- Two -->
			<!-- <section id="two" class="main special">
				<div class="container">
					<span class="image fit primary"><img src="" alt="" /></span>
					<div class="content">
						<header class="major">
							<h2>Tools Used</h2>
						</header>
						<p>The Application is built on Django, Plotly for statistical analysis and charts and Pandas for preprocessing the Data.</p>
						<ul class="icons-grid">
							<li>
								<span class="icon solid major fa-database"></span>
								<h3>Data</h3>
							</li>
							<li>
								<span class="icon solid major fa-chart-line"></span>
								<h3>Charts</h3>
							</li>
							<li>
								<span class="icon solid major fa-code"></span>
								<h3>Algo</h3>
							</li>
							<li>
								<span class="icon solid major fa-table"></span>
								<h3>Table</h3>
							</li>
						</ul>
					</div>
					<a href="#three" class="goto-next scrolly">Next</a>
				</div>
			</section> -->

		<!-- Three 
			<section id="three" class="main special">
				<div class="container">
					<span class="image fit primary"><img src="" alt="" /></span>
					<div class="content">
						<header class="major">
							<h2>What can you visualize</h2>
						</header>
						<p>Past Ten years of CPCB Data for the Ground Stations and its charts, some statistics like Mean, Median, Mode, Standard Deviation and cam also avail the functionality for downloading offline maps and charts.</p>
					</div>
					<a href="#footer" class="goto-next scrolly">Next</a>
				</div>
			</section>

		<!-- Four -->
		

		<!-- Footer -->
			<section id="footer">
				
				<footer>
					
				</footer>
			</section>

		<!-- Scripts -->
			<script src="{% static 'home/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'home/assets/js/jquery.scrollex.min.js' %}"></script>
			<script src="{% static 'home/assets/js/jquery.scrolly.min.js' %}"></script>
			<script src="{% static 'home/assets/js/browser.min.js' %}"></script>
			<script src="{% static 'home/assets/js/breakpoints.min.js' %}"></script>
			<script src="{% static 'home/assets/js/util.js' %}"></script>
			<script src="{% static 'home/assets/js/main.js' %}"></script>

	</body>
</html>

EduTrack/home/templates/home/login.html
 {% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Login</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'registration/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}" />
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'registration/css/style.css' %}" />
	</head>

	<body>

		<div class="wrapper">
			<div class="inner">
				<form action="{% url 'home:validate' %}" method="POST">
					{% csrf_token %}
					<h3>Login</h3>
					<p></p>
					<label class="form-group">
						<input type="text" name="username" class="form-control"  required>
						<span>Username</span>
						<span class="border"></span>
					</label>
					<label class="form-group">
						<input type="password" name="pass" class="form-control"  required>
						<span for="">Password</span>
						<span class="border"></span>
					</label>
					<!-- <label class="form-group" >
						<textarea name="" id="" class="form-control" required></textarea>
						<span for="">Your Message</span>
						<span class="border"></span>
					</label> -->
					<button>Login 
						<i class="zmdi zmdi-arrow-right"></i>
					</button>
				</form>
			</div>
		</div>
		
	</body>
</html>

EduTrack/home/templates/home/registration.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Registration</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'registration/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}" />
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'registration/css/style.css' %}" />
	</head>

	<body>

		<div class="wrapper">
			<div class="inner">
				<form action="{% url 'home:add_user' %}" method="POST">
					{% csrf_token %}
					<h3>Register Yourself</h3>
					<p></p>
					<label class="form-group">
						<input type="text" name="username" class="form-control"  required>
						<span>Username</span>
						<span class="border"></span>
					</label>
					<label class="form-group">
						<input type="password" name="password" class="form-control"  required>
						<span for="">Password</span>
						<span class="border"></span>
					</label>
					<!-- <label class="form-group" >
						<textarea name="" id="" class="form-control" required></textarea>
						<span for="">Your Message</span>
						<span class="border"></span>
					</label> -->
					<button>Register 
						<i class="zmdi zmdi-arrow-right"></i>
					</button>
				</form>
			</div>
		</div>
		
	</body>
</html>

EduTrack/home/templates/home/showplot.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'visualize/main.css' %}">
    <title>Plot</title>
</head>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: Arial, sans-serif;
    }

    .back-button {
        background-color: #3498db; /* Blue color */
        color: #fff; /* White text color */
        padding: 10px 20px; /* Adjust padding as needed */
        text-decoration: none;
        display: inline-block;
        margin: 20px; /* Adjust margin as needed */
        border-radius: 5px; /* Optional: Add rounded corners */
    }
    .plotly-graph-div {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.95)); /* Gradient background */
    border-radius: 12px; /* Rounded corners for a softer look */
    padding: 20px; /* Adjust padding as needed */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1), 0 0 20px rgba(0, 0, 0, 0.1); /* Box shadow for depth */
    margin: auto;
    /* Optional: Add transition for a smooth hover effect */
    transition: background 0.3s ease-in-out;
    }

    .plotly-graph-div:hover {
        background: linear-gradient(180deg, rgba(255, 255, 255, 0.95), rgba(255, 255, 255, 0.8)); /* Invert gradient on hover */
    }
</style>
<body>
    
    <a href="{% url 'home:ret' %}" class="back-button">Back</a>
    {{t|safe}}

    
    

</body>
</html>

EduTrack/home/templates/home/visualize.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Education Page</title>
    <link rel="stylesheet" href="{% static 'visualize/main.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Your custom CSS styles -->
    <style>

    </style>
</head>

<body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light" style="padding: 15px;">
        <a class="navbar-brand" href="#" style="font-size: 24px;">
            <strong>EduTrec</strong>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:logout' %}">
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    

    <!-- Content -->
    <div class="container">
        <div class="row">
            <!-- Cards -->
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Undergraduate</h5>
                        <a href="{% url 'home:plot' 'ug' 0 %}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'ug' 1 %}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Postgraduate</h5>
                        <a href="{% url 'home:plot' 'pg' 0 %}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'pg' 1 %}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Ph.D.</h5>
                        <a href="{% url 'home:plot' 'phd' 0 %}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'phd' 1 %}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">M-Phil.</h5>
                        <a href="{% url 'home:plot' 'mphil' 0%}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'mphil' 1%}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Diploma</h5>
                        <a href="{% url 'home:plot' 'di' 0 %}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'di' 1  %}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">PG Diploma</h5>
                        <a href="{% url 'home:plot' 'pgdi' 0 %}" class="btn btn-primary">Bar Chart</a>
                        <a href="{% url 'home:plot' 'pgdi' 1 %}" class="btn btn-primary">Pie Chart</a>
                    </div>
                </div>
            </div>
            <!-- Repeat the above card structure for other categories -->

        </div>
        <div class="row">
            <!-- Repeat the above card structure for other categories -->

        </div>
    </div>

    <!-- Footer -->
    <div class="footer">
        <p>Follow us on social media:</p>
        <a href="#" class="btn btn-light">Facebook</a>
        <a href="#" class="btn btn-light">Twitter</a>
        <a href="#" class="btn btn-light">LinkedIn</a>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>

</html>